# Tweaked version of gruvbox-material (sainnhe)
## Colorscheme for Helix - Focused on Windows Terminal
### Author: @rafaelrcamargo
#### License: Nah.

"attribute" = "aqua"
"comment" = "grey0"
"constant" = "purple"
"constant.character.escape" = "orange"
"constant.numeric" = "purple"
"constructor" = "yellow"
"function" = "green"
"function.builtin" = "blue"
"function.macro" = "aqua"
"keyword" = "red"
"keyword.directive" = "aqua"
"label" = "aqua"
"module" = "blue"
"namespace" = "aqua"
"operator" = "orange"
"punctuation" = "grey2"
"punctuation.bracket" = "fg0"
"punctuation.delimiter" = "grey2"
"special" = "orange"
"string" = "green"
"string.regexp" = "blue"
"tag" = "yellow"
"type" = "yellow"
"variable" = "fg0"
"variable.builtin" = "blue"
"variable.other.member" = "fg0"
"variable.parameter" = "fg0"

"markup.bold" = {modifiers = ["bold"]}
"markup.heading.1" = {fg = "red", modifiers = ["bold"]}
"markup.heading.2" = {fg = "orange", modifiers = ["bold"]}
"markup.heading.3" = {fg = "yellow", modifiers = ["bold"]}
"markup.heading.4" = {fg = "green", modifiers = ["bold"]}
"markup.heading.5" = {fg = "blue", modifiers = ["bold"]}
"markup.heading.6" = {fg = "fg", modifiers = ["bold"]}
"markup.heading.marker" = "grey2"
"markup.italic" = {modifiers = ["italic"]}
"markup.link.text" = "purple"
"markup.link.url" = {fg = "blue", modifiers = ["underlined"]}
"markup.list" = "red"
"markup.quote" = "grey2"
"markup.raw" = "green"

"diff.delta" = "orange"
"diff.minus" = "red"
"diff.plus" = "green"

"ui.background" = {bg = "bg_transparent"}
"ui.background.separator" = "grey0"
"ui.bufferline" = {fg = "grey0", bg = "bg1"}
"ui.bufferline.active" = {fg = "fg0", bg = "bg3", modifiers = ["bold"]}
"ui.cursor" = {fg = "bg0", bg = "fg0"}
"ui.cursor.insert" = {fg = "bg0", bg = "grey2"}
"ui.cursor.match" = {fg = "orange", bg = "bg_visual_yellow"}
"ui.cursor.select" = {fg = "bg0", bg = "blue"}
"ui.cursorline.primary" = {bg = "bg0.5"}
"ui.cursorline.secondary" = {bg = "bg1"}
"ui.help" = {fg = "fg0", bg = "bg2"}
"ui.linenr" = "grey0"
"ui.linenr.selected" = "fg0"
"ui.menu" = {fg = "fg0", bg = "bg3"}
"ui.menu.selected" = {fg = "bg0", bg = "blue", modifiers = ["bold"]}
"ui.popup" = {fg = "grey2", bg = "bg2"}
"ui.selection" = {bg = "bg3"}
"ui.statusline" = {fg = "fg0", bg = "bg3"}
"ui.statusline.inactive" = {fg = "grey0", bg = "bg1"}
"ui.statusline.insert" = {fg = "bg0", bg = "yellow", modifiers = ["bold"]}
"ui.statusline.normal" = {fg = "bg1", bg = "fg0", modifiers = ["bold"]}
"ui.statusline.select" = {fg = "bg0", bg = "blue", modifiers = ["bold"]}
"ui.text" = "fg0"
"ui.text.focus" = "fg0"
"ui.virtual.indent-guide" = {fg = "bg4"}
"ui.virtual.ruler" = {bg = "bg0.5"}
"ui.virtual.whitespace" = {fg = "bg4"}
"ui.window" = {fg = "grey0", bg = "bg0"}

"diagnostic" = {modifiers = ["underlined"]}
"error" = "red"
"hint" = "blue"
"info" = "aqua"
"warning" = "yellow"

[palette]
bg0 = "#292827"
"bg0.5" = "#313029"
bg1 = "#32302f"
bg2 = "#32302f"
bg3 = "#45403d"
bg4 = "#45403d"
bg5 = "#5a524c"

bg_current_word = "#3c3836"
bg_diff_blue = "#0e363e"
bg_diff_green = "#34381b"
bg_diff_red = "#402120"
bg_statusline1 = "#32302f"
bg_statusline2 = "#3a3735"
bg_statusline3 = "#504945"
bg_visual_blue = "#374141"
bg_visual_green = "#3b4439"
bg_visual_red = "#4c3432"
bg_visual_yellow = "#4f422e"

aqua = "#89b482"
bg_green = "#a9b665"
bg_red = "#ea6962"
bg_yellow = "#d8a657"
blue = "#7daea3"
fg0 = "#d4be98"
fg1 = "#ddc7a1"
green = "#a9b665"
orange = "#e78a4e"
purple = "#d3869b"
red = "#ea6962"
yellow = "#d8a657"

grey0 = "#7c6f64"
grey1 = "#928374"
grey2 = "#a89984"
